_extends: .github

repository:
  name: cron
  description: My cron scripts
  homepage: https://github.com/bjd2385/cron

  # A comma-separated list of topics to set on the repository
  topics: cron, bash, scripts
  private: false
